import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { fetchSystemStatus, SystemStatusResponse } from '../../api/systemStatusApi';
import { toStatusLabel, toStatusTone } from '../../utils/status';

type InsightEntry = { label: string; value: string };

const toEntries = (payload: unknown): InsightEntry[] => {
  if (!payload) return [];
  if (Array.isArray(payload)) {
    return payload
      .map((value, index) => ({
        label: `Item ${index + 1}`,
        value: typeof value === 'string' ? value : JSON.stringify(value),
      }))
      .filter((entry) => entry.value);
  }
  if (typeof payload === 'string') {
    return [{ label: 'Summary', value: payload }];
  }
  if (typeof payload === 'object') {
    return Object.entries(payload as Record<string, unknown>)
      .map(([key, value]) => ({
        label: key.replace(/_/g, ' '),
        value: typeof value === 'string' ? value : JSON.stringify(value),
      }))
      .filter((entry) => entry.value);
  }
  return [];
};

export const IntelligencePanel: React.FC = () => {
  const [status, setStatus] = useState<SystemStatusResponse | null>(null);
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);
  const mountedRef = useRef(true);

  const refresh = useCallback(async () => {
    setLoading(true);
    try {
      const response = await fetchSystemStatus();
      if (!mountedRef.current) return;
      setStatus(response);
      setError(null);
    } catch (err) {
      if (!mountedRef.current) return;
      setError(err instanceof Error ? err.message : 'Unable to load intelligence briefings');
    } finally {
      if (mountedRef.current) {
        setLoading(false);
      }
    }
  }, []);

  useEffect(() => {
    mountedRef.current = true;
    void refresh();
    // Set up polling to refresh intelligence every 15 seconds
    const intervalId = setInterval(() => {
      if (mountedRef.current) {
        void refresh();
      }
    }, 15000);
    return () => {
      mountedRef.current = false;
      clearInterval(intervalId);
    };
  }, [refresh]);

  const operationsInsights = useMemo(
    () => toEntries(status?.system_health?.operations_assessment),
    [status?.system_health?.operations_assessment],
  );
  const technicalInsights = useMemo(
    () => toEntries(status?.system_health?.technical_infrastructure),
    [status?.system_health?.technical_infrastructure],
  );
  const financialInsights = useMemo(
    () => toEntries(status?.system_health?.financial_health),
    [status?.system_health?.financial_health],
  );

  const agentPerformance = status?.system_health?.agent_performance;
  const overviewStatus = status?.system_health?.system_overview?.status;

  return (
    <section className="intelligence-panel">
      <header className="panel-header">
        <div>
          <h3>Executive Intelligence Briefing</h3>
          <span>Summaries generated by autonomous agents</span>
        </div>
        <div className="panel-header__actions">
          <span className={`status-pill status-pill--${toStatusTone(overviewStatus)}`}>
            {toStatusLabel(overviewStatus)}
          </span>
          <button type="button" className="refresh-button" onClick={() => void refresh()} disabled={loading}>
            {loading ? 'Refreshing...' : 'Refresh'}
          </button>
        </div>
      </header>

      {error && <p className="panel-error">{error}</p>}

      <div className="insights-grid">
        <article className="insight-card">
          <h4>Operations</h4>
          {operationsInsights.length === 0 && <p className="panel-empty">Operations team standing by.</p>}
          <ul>
            {operationsInsights.map((entry) => (
              <li key={entry.label}>
                <span>{entry.label}</span>
                <p>{entry.value}</p>
              </li>
            ))}
          </ul>
        </article>

        <article className="insight-card">
          <h4>Technical</h4>
          {technicalInsights.length === 0 && <p className="panel-empty">No technical alerts.</p>}
          <ul>
            {technicalInsights.map((entry) => (
              <li key={entry.label}>
                <span>{entry.label}</span>
                <p>{entry.value}</p>
              </li>
            ))}
          </ul>
        </article>

        <article className="insight-card">
          <h4>Financial</h4>
          {financialInsights.length === 0 && <p className="panel-empty">Financials ready for first inputs.</p>}
          <ul>
            {financialInsights.map((entry) => (
              <li key={entry.label}>
                <span>{entry.label}</span>
                <p>{entry.value}</p>
              </li>
            ))}
          </ul>
        </article>
      </div>

      {agentPerformance && (
        <footer className="intelligence-footer">
          <div>
            <span>Agent coordination</span>
            <strong>{agentPerformance.coordination_efficiency ?? 'N/A'}</strong>
          </div>
          <div>
            <span>Success rate</span>
            <strong>{agentPerformance.success_rate ?? 'N/A'}</strong>
          </div>
          <div>
            <span>Average response</span>
            <strong>{agentPerformance.avg_response_time ?? 'N/A'}</strong>
          </div>
        </footer>
      )}
    </section>
  );
};
